# @Exception

let foo32 = "no"
