# @exception expected closing ')' in call to 'delete'

delete(0, 1, 2)
